version: '3.8'
services:
  ts-database:
    container_name: ts-database
    image: mysql:8.0
    networks:
      - internal
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ts-db
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

networks:
  proxy:
    name: ts-proxy
    external: true
  internal:
    name: ts-internal
    external: false
